/*
** SQLite Opcodes - Minimal Stub for MongoLite
** 
** This is a minimal stub of opcodes.h containing only the definitions
** needed to compile global.c for the MongoLite storage engine.
** 
** The full opcodes.h is normally generated by mkopcodes.tcl from the
** SQL parser, but since MongoLite doesn't use SQL parsing, we only
** need minimal definitions.
*/
#ifndef OPCODES_H
#define OPCODES_H

/* Minimal opcode definitions needed by global.c */
#define OP_Noop                0   /* No operation */
#define OP_Explain             1   /* Explain query plan */
#define OP_Init                2   /* Initialize program */
#define OP_Goto                3   /* Jump unconditionally */
#define OP_Halt                4   /* Halt execution */

/* Maximum number of opcodes - minimal value */
#define OP_NOP_MAX 5

/* Opcode properties - all set to 0 for stub */
#define OPFLG_JUMP            0x01  /* jump:  P2 holds jmp target */
#define OPFLG_IN1             0x02  /* in1:   P1 is an input */
#define OPFLG_IN2             0x04  /* in2:   P2 is an input */
#define OPFLG_IN3             0x08  /* in3:   P3 is an input */
#define OPFLG_OUT2            0x10  /* out2:  P2 is an output */
#define OPFLG_OUT3            0x20  /* out3:  P3 is an output */

/* Stub opcode properties array - normally generated */
static const unsigned char sqlite3OpcodeProperty[] = {
    0,    /* OP_Noop */
    0,    /* OP_Explain */
    0,    /* OP_Init */  
    OPFLG_JUMP,  /* OP_Goto */
    0,    /* OP_Halt */
};

#endif /* OPCODES_H */